### ISSUE TITLE
Error: "Before testing, snapshot & fund"

### ISSUE THREAD

**Issue by suicide** [mangrovedao/hardhat-test-solidity#4]
I was running into an error:
```
  1) Shift_Test
       "before all" hook: Before testing, snapshot & fund Shift_Test for "shiftNegative":
     Error: Transaction reverted: function selector was not recognized and there's no fallback nor receive function
```

Adding
```
receive() external payable {}
```
to the test contract fixed it, just like in your test repo.
You might want to add this to the readme?

**Comment by adhusson** [comment]
Thanks a lot for the issue :) We added it to the README here 58bf6ae94f78c936510e3c9127f18d9da15449c7
